name: Deploy pythonanywhere webapp

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Re-Deploy Pythonanywhere Django API
        uses: umuttopalak/pythonanywhere-deploy-action@v1.1.0
        with:
          host: 'www.pythonanywhere.com'
          username: ${{ secrets.USERNAME }}
          api_token: ${{ secrets.API_TOKEN }}
          domain_name: ${{ secrets.DOMAIN_NAME }}
          working_directory: ${{ secrets.WORKING_DIRECTORY }}  # Reemplaza con la ruta correcta
          # Agregar un paso para ejecutar git pull con opciones adicionales
          run: |
            cd $WORKING_DIRECTORY
#            git pull
            git fetch
            git merge origin/main  # O la rama que corresponda
